package edu.uga.cs.countryquiz;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;
// comment for testing to commit

public class CountryData {
    public static final String TAG = "Country Data";
    private SQLiteDatabase db;
    private SQLiteOpenHelper countryDbHelper;

    private static final String[] allColumns = {
            CountryDBHelper.COUNTRIES_COLUMN_ID,
            CountryDBHelper.COUNTRIES_COLUMN_COUNTRY,
            CountryDBHelper.COUNTRIES_COLUMN_CONTINENT
    };
    public CountryData(Context context) {
        this.countryDbHelper = CountryDBHelper.getInstance(context);
    }
    public void open() {
        db = countryDbHelper.getWritableDatabase();
    }
    public void close() {
        if (countryDbHelper != null)
            countryDbHelper.close();
    }
    public Country storeCountry( Country country ) {
        ContentValues values = new ContentValues();
        values.put( CountryDBHelper.COUNTRIES_COLUMN_COUNTRY, country.getCountry());
        values.put( CountryDBHelper.COUNTRIES_COLUMN_CONTINENT, country.getContinent() );

        // Insert the new row into the database table; the id (primary key) will be
        // automatically generated by the database system and returned from db.insert

        long id = db.insert( CountryDBHelper.TABLE_COUNTRIES, null, values );
        // store the id in the country instance, as it is now persistent
        country.setId( id );
        return country;
    }

    public ArrayList<Country> retrieveAllCountries() {
        ArrayList<Country> countries = new ArrayList<>();
        Cursor cursor = null;
        int columnIndex;
        Log.i(TAG, "Executed");
        try {
            // Execute the select query and get the Cursor to iterate over the retrieved rows
            cursor = db.query(CountryDBHelper.TABLE_COUNTRIES, allColumns,
                    null, null, null, null, null);

            // collect all job leads into a List
            if (cursor != null && cursor.getCount() > 0) {

                while (cursor.moveToNext()) {

                    if (cursor.getColumnCount() >= 2) {

                        // get all attribute values of this job lead
                        columnIndex = cursor.getColumnIndex(CountryDBHelper.COUNTRIES_COLUMN_ID);
                        long id = cursor.getLong(columnIndex);
                        columnIndex = cursor.getColumnIndex(CountryDBHelper.COUNTRIES_COLUMN_COUNTRY);
                        String countryName = cursor.getString(columnIndex);
                        columnIndex = cursor.getColumnIndex(CountryDBHelper.COUNTRIES_COLUMN_CONTINENT);
                        String continent = cursor.getString(columnIndex);

                        // create a new Country object and set its state to the retrieved values
                        Country country = new Country(countryName, continent);
                        country.setId(id); // set the id (the primary key) of this object
                        // add it to the list
                        countries.add(country);
                        //Log.d(TAG, "Retrieved Country: " + country.getCountry());
                    }
                }
            }
        } finally {
            // we should close the cursor
            if (cursor != null) {
                cursor.close();
            }
        }
        // return a list of retrieved countries
        return countries;
    }
}
