package edu.uga.cs.countryquiz;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import java.util.ArrayList;
import java.util.List;

public class CountryData {
    private SQLiteDatabase db;
    private SQLiteOpenHelper countryDbHelper;

    private static final String[] allColumns = {
            CountryDbHelper.COUNTRIES_COLUMN_ID,
            CountryDbHelper.COUNTRIES_COLUMN_COUNTRY,
            CountryDbHelper.COUNTRIES_COLUMN_CONTINENT
    };
    public CountryData(Context context) {
        this.countryDbHelper = CountryDbHelper.getInstance(context);
    }
    public void open() {
        db = countryDbHelper.getWritableDatabase();
    }
    public void close() {
        if (countryDbHelper != null)
            countryDbHelper.close();
    }
    public Country storecountry( Country country ) {
        ContentValues values = new ContentValues();
        values.put( countryDbHelper.COUNTRIES_COLUMN_COUNTRY, country.getCountry());
        values.put( countryDbHelper.COUNTRIES_COLUMN_CONTINENT, country.getContinent() );

// Insert the new row into the database table; the id (primary key) will be
// automatically generated by the database system and returned from db.insert
//
        long id = db.insert( countryDbHelper.TABLE_COUNTRIES, null, values );
// store the id in the country instance, as it is now persistent
        country.setId( id );
        return country;
    }

    public List<Country> retrieveAllCountrys() {
        ArrayList<Country> Countrys = new ArrayList<>();
        Cursor cursor = null;
        cursor = db.query(countryDbHelper.TABLE_COUNTRIES, allColumns,
                null, null, null, null, null);
        while (cursor.moveToNext()) {
            long id = cursor.getLong(cursor.getColumnIndex(countryDbHelper.COUNTRIES_COLUMN_ID));
            String country = cursor.getString(cursor.getColumnIndex(countryDbHelper.COUNTRIES_COLUMN_COUNTRY));
            String continent = cursor.getString(cursor.getColumnIndex(countryDbHelper.COUNTRIES_COLUMN_CONTINENT));
            Country Country = new Country(country, continent);
            Country.setId(id);
            Countrys.add(Country);
        }
    }
}
